version: '3.5'

services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile-client
    ports:
      - '3000:3000'
    volumes:
      - .:/src
      - '/src/node_modules'
