version: '3.5'

services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile-client
    ports:
      - '3000:3000'
    volumes:
      - .:/src
      - '/src/node_modules'

  fpm:
    container_name: php-fpm
    build:
      context: .docker/
      dockerfile: Dockerfile-php
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/Ochildren
    volumes:
      - symfony-sync:/var/www/project/
    networks:
      - symfony
    depends_on:
      - mysql

  apache:
    container_name: apache
    image: symfony_apache
    build:
      context: .docker/
      dockerfile: Dockerfile-apach
    ports:
      - 8080:80
    volumes:
      - symfony-sync:/var/www/project/:nocopy
    depends_on:
      - fpm
    networks:
      - symfony

  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - '4003:3306'
    expose:
      - '3306'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    # tty: true
    networks:
      - symfony

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:db
    ports:
      - 8181:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql

volumes:
  symfony_db:
  symfony-sync:

networks:
  symfony:
