version: '3.5'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
      volumes:
        - ./:/src
        - /src/node_modules
    ports:
      - '3000:3000'
